[Errno 122] Disk quota exceeded: '/homes2/informatik/herzig/.cache/huggingface/transformers/07e398f6c4f4eb4f676c75befc5ace223491c79cea1109fb4029751892d380a1.bc3155ca0bae3a39fc37fc6d64829c6a765f46480894658bb21c08db6155358d.lock'
Traceback (most recent call last):
  File "/work/herzig/torch_env/lib/python3.9/site-packages/transformers-4.8.1-py3.8.egg/transformers/feature_extraction_utils.py", line 351, in get_feature_extractor_dict
  File "/work/herzig/torch_env/lib/python3.9/site-packages/transformers-4.8.1-py3.8.egg/transformers/file_utils.py", line 1329, in cached_path
  File "/work/herzig/torch_env/lib/python3.9/site-packages/transformers-4.8.1-py3.8.egg/transformers/file_utils.py", line 1563, in get_from_cache
  File "/work/herzig/torch_env/lib/python3.9/site-packages/filelock.py", line 323, in __enter__
    self.acquire()
  File "/work/herzig/torch_env/lib/python3.9/site-packages/filelock.py", line 271, in acquire
    self._acquire()
  File "/work/herzig/torch_env/lib/python3.9/site-packages/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
OSError: [Errno 122] Disk quota exceeded: '/homes2/informatik/herzig/.cache/huggingface/transformers/07e398f6c4f4eb4f676c75befc5ace223491c79cea1109fb4029751892d380a1.bc3155ca0bae3a39fc37fc6d64829c6a765f46480894658bb21c08db6155358d.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/herzig/asr_dysarthria/script/evaluate.py", line 41, in <module>
    main()
  File "/work/herzig/asr_dysarthria/script/evaluate.py", line 13, in main
    processor, model, device = get_model(args.l, args.m, args.local)  # Load tokenizer and model
  File "/net/work/herzig/asr_dysarthria/script/helper/get_model.py", line 11, in get_model
    processor = Wav2Vec2Processor.from_pretrained(MODEL_ID)
  File "/work/herzig/torch_env/lib/python3.9/site-packages/transformers-4.8.1-py3.8.egg/transformers/models/wav2vec2/processing_wav2vec2.py", line 104, in from_pretrained
  File "/work/herzig/torch_env/lib/python3.9/site-packages/transformers-4.8.1-py3.8.egg/transformers/feature_extraction_utils.py", line 281, in from_pretrained
  File "/work/herzig/torch_env/lib/python3.9/site-packages/transformers-4.8.1-py3.8.egg/transformers/feature_extraction_utils.py", line 373, in get_feature_extractor_dict
OSError: Can't load feature extractor for 'facebook/wav2vec2-base-960h'. Make sure that:

- 'facebook/wav2vec2-base-960h' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'facebook/wav2vec2-base-960h' is the correct path to a directory containing a preprocessor_config.json file


